#!/usr/bin/env zsh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/lib"

info "Installing Superpowers plugin in antigravity"
agy plugin install https://github.com/obra/superpowers &> /dev/null ||
  error "Failed to install Superpowers plugin."

success "Superpowers plugin installed"

