#!/usr/bin/env zsh

source "${0:a:h}/../tools/lib"

info "Installing Superpowers plugin in antigravity"
agy plugin install https://github.com/obra/superpowers &> /dev/null ||
  error "Failed to install Superpowers plugin."

success "Superpowers plugin installed"

